### PR TITLE
WIP: Refactor

### PR DESCRIPTION
**Pull request by kumarstack55**
The current codes has the following:

* Code that will not be executed exists.
* Multiple copies of the same process exist.
* Mutable variables exist.
* There are questions.

and so on.

Such code may hinder future modifications. 😷 

In this pull request, please let me modify the codes without changing the existing functionality.

@wsdjeg : If you agree, it would be helpful if you could respond in the comments. 😎 👍

### CODE REVIEW

**Comment by wsdjeg** [comment]
thanks，I'm ok.
在 2020年6月7日 18:33，kumarstack55 <notifications@github.com>写道：<br type="attributi

The current codes has the following:

  *   Code that will not be executed exists.
  *   Multiple copies of the same process exist.
  *   Mutable variables exist.
  *   There are questions.

and so on.

Such code may hinder future modifications. 😷

In this pull request, please let me modify the codes without changing the existing functionality.

@wsdjeg<https://github.com/wsdjeg> : If you agree, it would be helpful if you could respond in the comments. 😎 👍

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/wsdjeg/mdctags.rs/pull/15

Commit Summary

  *   Add test for Line::split()
  *   Refactor Line::split()

File Changes

  *   M src/main.rs<https://github.com/wsdjeg/mdctags.rs/pull/15/files#diff-639fbc4ef05b315af92b4d836c31b023> (22)

Patch Links:

  *   https://github.com/wsdjeg/mdctags.rs/pull/15.patch
  *   https://github.com/wsdjeg/mdctags.rs/pull/15.diff

**Comment by kumarstack55** [comment]
You can run tests, builds and bats tests with this command.

```bash
cargo test && cargo build && bats test
```

@wsdjeg : It would be helpful if you could merge this pull request. 😎 👍 ✨

**Comment by wsdjeg** [comment]
thanks for your work. Is it ready  to be merged?

**Comment by kumarstack55** [comment]
> thanks for your work. Is it ready to be merged?

Ready to go. :sparkles:
Please merge. :+1:

**Pull request merged**
